drop TABLE SALES_SOURCE_DATA;
CREATE TABLE SALES_SOURCE_DATA
(employee_id 	NUMBER(6),
WEEK_ID	NUMBER(2),
SALES_MON	NUMBER(8,2),
SALES_TUE	NUMBER(8,2),
SALES_WED	NUMBER(8,2),
SALES_THUR	NUMBER(8,2),
SALES_FRI	NUMBER(8,2));