CREATE TABLE EMP_UNNAMED_INDEX
  (
    employee_id NUMBER(6) PRIMARY KEY ,
    first_name  VARCHAR2(20),
    last_name   VARCHAR2(25)
  );
SELECT INDEX_NAME,
  TABLE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'EMP_UNNAMED_INDEX';