DROP TABLE sales_dept CASCADE CONSTRAINTS;
CREATE TABLE SALES_DEPT 
       (team_id NUMBER(3)
       PRIMARY KEY USING INDEX
       (CREATE INDEX sales_pk_idx ON
        SALES_DEPT(team_id)),
        location VARCHAR2(30));
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME = 'SALES_DEPT';
