DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY 
   (	"CATEGORY_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"CATEGORY_DESCRIPTION" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID"))