DECLARE
	V_MESSAGE VARCHAR2(35);
	V_DATE_WRITTEN DATE;
       BEGIN
	V_MESSAGE := 'This is my first PLSQL Program';
	V_DATE_WRITTEN := SYSDATE;
	INSERT INTO temp(CHAR_STORE,DATE_STORE)
	VALUES (V_MESSAGE,V_DATE_WRITTEN);
END;
/
SELECT * FROM TEMP;