SET SERVEROUTPUT ON
DECLARE
  V_SAL        NUMBER(7,2) := &B_SALARY;
  V_BONUS      NUMBER(7,2);
  V_ANN_SALARY NUMBER(15,2);
BEGIN
  V_ANN_SALARY       := V_SAL * 12;
  IF V_ANN_SALARY    >= 20000 THEN
    V_BONUS          := 2000;
  ELSIF V_ANN_SALARY <= 19999 AND V_ANN_SALARY >=10000 THEN
    V_BONUS          := 1000;
  ELSE
    V_BONUS := 500;
  END IF;
  DBMS_OUTPUT.PUT_LINE ('The Bonus is $  ' || TO_CHAR(V_BONUS));
END;
/