CREATE OR REPLACE PACKAGE state_tax IS
   ma CONSTANT NUMBER := 0.05;
   ny CONSTANT NUMBER := 0.08;
    nj CONSTANT NUMBER := 0.07;
    pa CONSTANT NUMBER := 0.05;
    dc CONSTANT NUMBER := 0.06;
END state_tax;