-- In order to be able to run this example, you need to ensure that you have the 
-- following privileges (granted by sys/oracle) if you are logged in as user ora61: 
-- GRANT CREATE TRIGGER TO ora61
-- GRANT ALTER ANY TRIGGER TO ora61
-- GRANT DROP ANY TRIGGER TO ora61
-- GRANT ADMINISTER DATABASE TRIGGER TO ora61

CREATE TABLE ddl_history
(USER_NAME varchar2(30),EVENT_DATE timestamp,
SYS_EVENT varchar2(30),OBJECT_TYPE varchar2(30),
OBJECT_NAME varchar2(30),ERROR_CODE VARCHAR2(30),
STATEMENT VARCHAR2(4000),ERROR_TEXT VARCHAR2(4000));
/
CREATE OR REPLACE TRIGGER DDL_TRIGGER
AFTER CREATE OR ALTER OR DROP or SERVERERROR
ON DATABASE
WHEN (RTRIM(USER)<>'SYS' AND RTRIM(USER)<>'SYSTEM')
DECLARE
STMT VARCHAR2(20000);
SQL_TEXT ORA_NAME_LIST_T;
N NUMBER;
BEGIN
N:=ORA_SQL_TXT(SQL_TEXT);
FOR I IN 1..N LOOP
STMT:=STMT||SQL_TEXT(I);
END LOOP;
INSERT INTO ddl_history
(USER_NAME,EVENT_DATE,SYS_EVENT,OBJECT_TYPE,OBJECT_NAME,
ERROR_CODE,STATEMENT,ERROR_TEXT)
VALUES(ORA_LOGIN_USER,CURRENT_TIMESTAMP,ORA_SYSEVENT,
ORA_DICT_OBJ_TYPE,ORA_DICT_OBJ_NAME,
ORA_SERVER_ERROR(1),STMT,ORA_SERVER_ERROR_MSG(1));
END;

