SET SERVEROUTPUT ON

DECLARE
code CONSTANT VARCHAR2(32767) :=
' CREATE OR REPLACE PROCEDURE new_proc AS 
  V_DATE  DATE;  
  BEGIN 
    V_DATE := SYSDATE;
    DBMS_OUTPUT.PUT_LINE(V_DATE) ;
  END; ' ;
BEGIN
  DBMS_DDL.CREATE_WRAPPED (CODE);
END;
/